// Action Types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNOUT_ERROR = 'SIGNOUT_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE';
export const FETCH_SEARCHED_MOVIES = 'FETCH_SEARCHED_MOVIES';
export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const SET_CURRENT_PAGE_NUMBER = 'SET_CURRENT_PAGE_NUMBER';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_REQUESTED = 'FETCH_MOVIES_REQUESTED';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';
export const ADD_TO_WATCH_LIST = 'ADD_TO_WATCH_LIST';
export const ADD_TO_WATCH_LIST_ERROR = 'ADD_TO_WATCH_LIST_ERROR';
export const REMOVE_FROM_WATCH_LIST = 'REMOVE_FROM_WATCH_LIST';
export const REMOVE_FROM_WATCH_LIST_ERROR = 'REMOVE_FROM_WATCH_LIST_ERROR';
export const RESET_CURRENT_MOVIE = 'RESET_CURRENT_MOVIE';
export const RESET_MAIN_MOVIE_LIST = 'RESET_MAIN_MOVIE_LIST';
export const ADD_NOTIFICATION_ADD_TO_WATCH_LIST = 'ADD_NOTIFICATION_ADD_TO_WATCH_LIST';
export const ADD_NOTIFICATION_AVOID_DUPLICATES = 'ADD_NOTIFICATION_AVOID_DUPLICATES';
export const ADD_NOTIFICATION_LOGIN_SUCCESS = 'ADD_NOTIFICATION_LOGIN_SUCCESS';
export const ADD_NOTIFICATION_SIGNUP_SUCCESS = 'ADD_NOTIFICATION_SIGNUP_SUCCESS';
export const ADD_NOTIFICATION_REMOVED_FROM_WATCH_LIST = 'ADD_NOTIFICATION_REMOVED_FROM_WATCH_LIST';


